# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
      gradle(
        task: 'bundle',
        build_type: 'Release',
        properties: {
          "android.injected.signing.store.file" => ENV[KEY_JKS],
          "android.injected.signing.store.password" => ENV[KEY_PASSWORD],
          "android.injected.signing.key.alias" => ENV[KEY_ALIAS],
          "android.injected.signing.key.password" => ENV[KEY_ALIAS_PASSWORD]
        }
      )

      upload_to_play_store(
        track: 'beta',
        json_key_data: ENV[SERVICE_ACCOUNT]
      )
  end
end
